### ISSUE TITLE
Tutorial4の動作に関して

### ISSUE THREAD

**Issue by hamar1** [SonyCSL/OpenECHO-cpp#1]
デバイス組込に際して、java版OpenECHOからc++への移行を試みており、
Java版DefaultControllerとC++版LightEmulator(tutorial4/main.cpp)を動かして動作確認を行っています。
つきましてはC++版のプログラムに関する質問がありますので、お答えいただけると幸いです。

１．Tutorial4/main.cppの基本動作に関して
元のコード機能は、一般照明をエミュレートし、自身のnode情報をネットワーク内のEchonetLite機器にinformし、照明オンオフ指令を取得できた場合、指令内容を実行し、プリントする。但し、情報を取得する機能は実装されていない(addEventListnerがコメントアウトされているため)。という認識で正しいでしょうか。

２．他ノードの情報取得に関して
【症状】
自ノード(tutorial/main.cppライトエミュレータ)の発信する情報は取得できるが、他ノード(java版コントローラ)の発見および他ノードの発信する情報を取得できない。
他ノード側(java版コントローラ)では自ノード(ライトエミュレータ)の情報の取得に成功している。
【手順】
tutorial4/main.cppの193行目Echo::addEventListnerのコメントアウトを解除し、makefileでmakeして実行。

上記の症状に対して、他nodeによる情報取得を行うために実装を行うorコメントアウトを外す必要のあるプログラムファイルおよび内容をお教えいただけないでしょうか。

以上、よろしくおねがいします。

**Comment by sowd** [comment]
申し訳ありません、現在調査中です。
何かわかりましたらご連絡差し上げます。

**Comment by hamar1** [comment]
修正頂きありがとうございます。
他ノードの情報の取得に成功いたしました。

また何かしらありましたらよろしくお願いします。

**Comment by sowd** [comment]
ご対応が遅くなり大変申し訳ありません。問題の特定に時間がかかりました。現状このようなコメントが来ています：

===================-
動作がおかしい点があったので修正しました．constの有無が原因で，いつ頃からかうまく動いてなかったようです．

質問に対しては，
1は正しく，addEventListnerを有効にすれば図のように他ノード(192.168.179.11)からの電文も表示されるはず．
2は，今回修正した内容では直らないと思いますが，マージしたソースで試してみてください．
あと，動作確認したpcは，自ノードはOS X EI Capitan，他ノードはKadecotです．ビルドはEclipse IDE for C/C++ Developersを利用しました．

![tutorial4-log](https://cloud.githubusercontent.com/assets/1326876/19280032/f50f3f7a-901e-11e6-81a8-c906f1539d42.png)
